fix: replace uint8_t with unsigned char in CVE-2026-58010.patch and CVE-2026-58013.patch
Both patches used uint8_t type which requires <stdint.h>. The test files (glib/tests/gvariant.c and glib/tests/io-channel.c) don't include that header, causing build failures:
  ../../../glib/tests/gvariant.c:5789:3: error: unknown type name 'uint8_t'
  ../../../glib/tests/io-channel.c:234:3: error: unknown type name 'uint8_t'

Replaced with 'unsigned char' which is a standard C type available without extra includes.