fix: replace uint8_t with unsigned char in CVE-2026-58015.patch
The CVE-2026-58015 patch for gdbusauthmechanismsha1.c used (uint8_t) cast which requires <stdint.h>. Since the file does not include that header, replace with (unsigned char) which is a standard C type available without any extra includes.

This fixes the build error:
  ../../../gio/gdbusauthmechanismsha1.c:1215:12: error: 'uint8_t' undeclared (first use in this function)